# Generated by Django 3.2.7 on 2022-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220521_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputationsespeces',
            name='date_imputation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'client'), ('controlleur', 'controlleur'), ('createur_client', 'createur_client'), ('admin', 'admin')], max_length=255),
        ),
    ]
