# Generated by Django 3.2.7 on 2022-05-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220522_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imputationsespeces',
            name='date_imputation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
